### ISSUE TITLE
What are instances in Blob_loss function?

### ISSUE THREAD

**Issue by Joeycho** [neuronflow/blob_loss#4]
Hi, thanks for sharing newly designed loss function in medical segmentation!

I have followed the the code, and I just wonder what are the instances in the code.

https://github.com/neuronflow/blob_loss/blob/6020a66b7503c6d2e364f7c5f5ae28e22ab8dff3/blob_loss.py#L91

If I understood the above code correctly, it looks like multi-labels contains how many instances are there. So, is this the number of ground truth instances? 

```py
multi_label.shape[0] # is this number of instances from ground truth label?
```
The confusing point is whether it is needed to separate each component from one ground truth label. Let's say, tumor in brain, and it has 10 tumors in brain but it is labeled in one single 3D nifti file. Maybe it is needed to be transformed  into the shape"[10, depth, height, width]" to be used for blob function which you provided.

My follow-up question is .. then.. prediction has typically unmatched number of instances compared to ground truth labels. Have you considered this as well? Like, prediction might has over 20 tumors instances compared to 10 ground truth. Although one can list them from biggest component to smallest and try to map with ground truth, I am not sure whether they could be properly compared.

I think I missunderstand big part in your code from the beginning. I will be appreciated if you can clarify. I liked the idea in blob_loss, penalizing more FP along increasing the number of instances. Since I've also observed in my task, there are a lot of FP scattered or connected part in predictions. I hope I can get some idea from your research.

Best
Joey

**Comment by neuronflow** [comment]
Hi,

thanks for your interest in blob loss.

Here we start to loop through the instances:
https://github.com/neuronflow/blob_loss/blob/6020a66b7503c6d2e364f7c5f5ae28e22ab8dff3/blob_loss.py#L110

You can organize your blob labels in a single label nifti file. For the manuscript, I used this tool for preprocessing:
https://github.com/seung-lab/connected-components-3d

Hope this helps, sorry for the brevity working on a paper deadline atm :)

**Comment by Joeycho** [comment]
Thanks for quick reply! Yes, now it makes sense to me! And you masked out on each prediction per each instance from labels. I meant that you don't apply the same preprocessing on prediction, only on a single label.
